global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: "system-monitor-agent"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
